[package]
name = "wye"
version = "0.1.0"
edition = "2024"

[dependencies]
mio = { version = "1", features = ["os-ext", "os-poll"] }
nix = { version = "0.30", features = ["fs", "ioctl", "process", "signal", "term"] }

[profile.release]
opt-level = "z"
strip = true
codegen-units = 1
