[package]
name = "wye"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { version = "0.30", features = ["fs", "ioctl", "process", "term"] }
libc = "0.2"

[profile.release]
opt-level = "z"
strip = true
codegen-units = 1
